<div id="controls">
    <button class="record-buttons" id="recordButton">Record</button>
    <button class="record-buttons" id="pauseButton" >Pause</button>
    <button class="record-buttons" id="stopButton" >Stop</button>
</div>
<script type="text/javascript">
    
        require([
            "jquery",        
            "VoiceQr_Record/js/record"
        ], function(){        
        });
    
</script>
