<!-- <div id="controls">
    <button class="record-buttons" id="recordButton">Record</button>
    <button class="record-buttons" id="pauseButton" >Pause</button>
    <button class="record-buttons" id="stopButton" >Stop</button>
    
</div>

<div>
<ol id="recordingsList"></ol>
<div id="qrcode"></div>

</div> -->
<form class="" action="<?php echo $block->getBaseUrl().'voiceqr/index/save'; ?>" id="vky-test-form" method="post" enctype='multipart/form-data'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For Vky_Test Module</span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field title">
            <label class="label" for="title"><span>Title</span></label>
            <div class="control">
                <input name="title" id="title" title="Name" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Author</span></label>
            <div class="control">
                <input name="author" id="author" title="Author" value="" class="input-text" type="text">
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span>Content</span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" cols="5" rows="3"></textarea>
            </div>
        </div>
        <div class="field image">
            <label class="label" for="image"><span>Image</span></label>
            <div class="control">
                <input name="image" id="image" title="Image" value="" class="input-file" type="file">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>

<!-- <script type="text/javascript">
        require([
            'jquery',   
            'recorder',
            'record'
            
        ], function(){        

        });
</script> -->